import { buildModule } from "@nomicfoundation/hardhat-ignition/modules";

export default buildModule(
  "SecureVaultModule",
  (m) => {
    const initialOwner = m.getAccount(0); // Getting the first account generated by hardhat
    // const initialOwner = m.getParameter("initialOwner");
    // const initialOwner = "0x385e82012850EF05222EC2392E3aD806E9F04C26"; // Metamask account
    const vault = m.contract("SecureVault", [initialOwner]);

    return { vault };
  }
);